name: 'Dump-packagejson-version'
author: 'PiQuark6046 and contributors'
description: 'Dump the version of package.json to the version defined in the tags connected to the triggered release'

inputs:
  package-json-path:
    description: 'A single package.json file to dump the version to'
    required: false
    default: 'package.json'

runs:
  using: 'composite'
  steps:
    - name: Install npm packages
      run: |
        npm i
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Dump version of package.json to version defined in tags connected to triggered release
      run: |
        npm run ci -- --tag "$TAG" --package-json-path "$PACKAGE_JSON_PATH" --workspace-path "$WORKSPACE_PATH"
      shell: bash
      env:
        TAG: ${{ github.ref_name }}
        PACKAGE_JSON_PATH: ${{ inputs.package-json-path }}
        WORKSPACE_PATH: ${{ github.workspace }}
      if: github.ref_type == 'tag'
      working-directory: ${{ github.action_path }}
